version: '3'


volumes:
  postgres:
  nest-node-modules:
  next-node-modules:
  postgres-devel:
  redis-devel:

networks:
  docker-network:

services:
  postgres:
    image: postgres:latest
    env_file: env_files/postgres.develop.env
    volumes:
      - type: volume
        source: postgres-devel
        target: /var/lib/postgresql/data
    networks:
      - docker-network
    
  redis:
    image: redis:latest
    volumes:
      - type: bind
        source: config/redis/redis.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: redis-devel
        target: /data
    networks:
      - docker-network

  nest:
    container_name: nestcontainer-devel
    build:
      context: .
      dockerfile: Dockerfiles/NestJS-develop-Dockerfile
    env_file: env_files/nestjs.develop.env
    ports:
      - 5555:5555 # for prisma studio
    volumes:
      - type: bind
        source: ${NESTDIR}
        target: /home/

      - type: volume
        source: nest-node-modules
        target: /home/node_modules/
    networks:
      - docker-network

  next:
    container_name: nextcontainer-devel
    build: 
      context: .
      dockerfile: Dockerfiles/NextJS-develop-Dockerfile
    volumes:
      - type: bind
        source: ${NEXTDIR}
        target: /home/

      - type: volume
        source: next-node-modules
        target: /home/node_modules/
    networks:
      - docker-network

  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: config/nginx
        target: /etc/nginx/conf.d
    networks:
      - docker-network


