version: '3'


volumes:
  postgres:
  nest-node-modules:
  next-node-modules:
  postgres-store:

networks:
  docker-network:

services:
  postgres:
    image: postgres:latest
    env_file: env_files/postgres.env
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-store
        target: /var/lib/postgresql/data
    networks:
      - docker-network

  nest:
    build:
      context: .
      dockerfile: Dockerfiles/NestJS-Dockerfile
    volumes:
      - type: bind
        source: ${NESTDIR}
        target: /home/

      - type: volume
        source: nest-node-modules
        target: /home/node_modules/
    networks:
      - docker-network

  next:
    build: 
      context: .
      dockerfile: Dockerfiles/NextJS-Dockerfile
    volumes:
      - type: bind
        source: ${NEXTDIR}
        target: /home/

      - type: volume
        source: next-node-modules
        target: /home/node_modules/
    networks:
      - docker-network

  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: config/nginx
        target: /etc/nginx/conf.d
    networks:
      - docker-network


