version: '3'


volumes:
  postgres:
  nest-node-modules:
  next-node-modules:
  postgres-store:


services:

  postgres:
    image: postgres:latest
    env_file: env_files/postgres.env
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-store
        target: /var/lib/postgresql/data

        
  nest:
    build:
      context: .
      dockerfile: Dockerfiles/NestJS-Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ${NESTDIR}
        target: /home/

      - type: volume
        source: nest-node-modules
        target: /home/node_modules/

  next:
    build: 
      context: .
      dockerfile: Dockerfiles/NextJS-Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ${NEXTDIR}
        target: /home/

      - type: volume
        source: next-node-modules
        target: /home/node_modules/


